config/routes.rb
TransTest::Application.routes.draw do

  

   scope "(/:locale)" do
     resource :trans_dots
     root :to => "trans_dots#index"
   end

end

app/models/trans_dot.rb
class TransDot < ActiveRecord::Base


  #mark change after ernst 1

#blabla from ernst

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter  :set_locale
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end

  def set_locale
    logger.debug "Param locale = " + (params[:locale]==nil ? "nil" : params[:locale].to_s)
    logger.debug "Session locale = " + (session[:locale] ==nil ? "nil" : session[:locale].to_s)
    I18n.locale = session[:locale] = params[:locale] || session[:locale] || :en #extract_locale_from_accept_language_header
    logger.info "Locale set to " + I18n.locale.to_s
  end
end

app/controllers/trans_dots_controller.rb
class TransDotsController < ApplicationController
  # GET /trans_dots
  # GET /trans_dots.xml
  #before_filter :authenticate_user!

  @@model_translation_code =$ARM #+ "trans_dot.one"
  
  def index
    @trans_dots = TransDot.paginate(:page => params[:page], :per_page=>15)  #TransDot.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trans_dots }
    end
  end

  # GET /trans_dots/1
  # GET /trans_dots/1.xml
  def show
    @trans_dot = TransDot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @trans_dot }
    end
  end

  # GET /trans_dots/new
  # GET /trans_dots/new.xml
  def new
    @trans_dot = TransDot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trans_dot }
    end
  end

  # GET /trans_dots/1/edit
  def edit
    @trans_dot = TransDot.find(params[:id])
  end

  # POST /trans_dots
  # POST /trans_dots.xml
  def create
    @trans_dot = TransDot.new(params[:trans_dot])

    respond_to do |format|
      if @trans_dot.save
        flash[:success] = t('messages.create.success', :model=>t(@@model_translation_code))          
        format.html { redirect_to( :action => "index")} #(@trans_dot #, :notice => 'Trans dot was successfully created.') }
        format.xml  { render :xml => @trans_dot, :status => :created, :location => @trans_dot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trans_dot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trans_dots/1
  # PUT /trans_dots/1.xml
  def update
    @trans_dot = TransDot.find(params[:id])

    respond_to do |format|
      if @trans_dot.update_attributes(params[:trans_dot])
        flash[:success] = t('messages.update.success', :model=>t(@@model_translation_code))
        format.html { redirect_to( :action => "index")} #(@trans_dot, :notice => 'Trans dot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trans_dot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trans_dots/1
  # DELETE /trans_dots/1.xml
  def destroy
    @trans_dot = TransDot.find(params[:id])
    @trans_dot.destroy

    respond_to do |format|
      format.html { redirect_to(trans_dots_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  $A="actions."
  $AR="activerecord."
  $ARA=$AR + "attributes."
  $ARM= $AR + "models."
  $F="formtastic."
  $FL= $F+"labels."
  $FH=$F+"hints."
  $L="links."
  $LU="lookups."
  $M="menus."
  $MS="messages."
  $MSE=$MS+"errors."
  $REDIS_PW='123456'

=begin
  This code will facilitate i18n in will_paginate
  just substitute twill_paginate for will_paginate
=end
  def twill_paginate(collection = nil, options = {})
      will_paginate collection, {:previous_label => t('commons.previous'), :next_label => t('commons.next')}.merge(options)
  end
end

app/helpers/trans_dots_helper.rb
module TransDotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TransTest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trans_dots/_form.html.erb
<%= semantic_form_for(@trans_dot) do |f| %>
  <!--%%= error_count_display @< %=singular_table_name%>, t("actions.save", :model=> t($ARM + "< %=singular_table_name%>", :count=>1) ) %> -->


  <!-- %%= error_list @singular_table_name %> -->
  
	<% f.inputs do %>
				   <%= f.input :name  %>   
				   <%= f.input :description  %>   
				   <%= f.input :do_this  %>   
		
	<% end %>	
	<%= f.buttons do %>
      <%= f.commit_button  %>    
  <% end %>
	
	<% end %>

app/views/trans_dots/edit.html.erb
<p class="pageheading"><%=t("headings.edit.heading", :model=>t($ARM + "trans_dot", :count=>1) )%></p>
<%= render 'form' %>
<%= link_to t('headings.new.heading', :model=> t($ARM + 'trans_dot', :count=>1)), new_trans_dot_path %> |
<%= link_to t("actions.back"), trans_dots_path %>

app/views/trans_dots/index.html.erb
<p class="pageheading"><%=t("headings.listing.heading", :model=>t($ARM + "trans_dot", :count=>2) )%></p>

<%= twill_paginate %>
<table class="data">
  <tr class="dataheader">

    <th class ="dataheader"><%=t($ARA + 'trans_dot.name') %></th>

    <th class ="dataheader"><%=t($ARA +'trans_dot.description') %></th>

    <th class ="dataheader"><%=t($ARA +'trans_dot.do_this') %></th>

    <th class="linkheader"></th>
    <th class="linkheader"></th>
    
  </tr>

  
<% cell_class = "data" %>
<% link_cell_class="link"%>  
<% @trans_dots.each do |trans_dot| %>

  <tr class = "<%= cycle('dataeven', 'dataodd') %>" >
  
      <td class="<%= cell_class %>"><%= trans_dot.name %></td>

  
      <td class="<%= cell_class %>"><%= trans_dot.description %></td>

  
      <td class="<%= cell_class %>"><%= trans_dot.do_this %></td>

  
    
    <td class="<%= link_cell_class %>"><%= link_to  t('actions.edit'), edit_trans_dots_path(trans_dot) %></td>
    <td class="<%= link_cell_class %>"><%= link_to t('actions.destroy'),  trans_dot , :confirm => t('messages.delete.are_you_sure', :model => t($ARM + "trans_dot", :count=>1)), :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= twill_paginate %>

<br />
<%= link_to t('headings.new.heading', :model=> t($ARM + 'trans_dot', :count=>1)), new_trans_dots_path %>

app/views/trans_dots/new.html.erb
<p class="pageheading"><%= t("headings.new.heading", :model=>t($ARM + "trans_dot", :count=>1))%></p>
<%= render 'form' %>
<%= link_to t('headings.new.heading', :model=> t($ARM + 'trans_dot', :count=>1)), new_trans_dot_path %> |
<%= link_to t("actions.back"), trans_dots_path %>

app/views/trans_dots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @trans_dot.name %>
</p>

<p>
  <b>Description:</b>
  <%= @trans_dot.description %>
</p>

<p>
  <b>Do this:</b>
  <%= @trans_dot.do_this %>
</p>


<%= link_to 'Edit', edit_trans_dot_path(@trans_dot) %> |
<%= link_to 'Back', trans_dots_path %>